from odoo import models


class LLMProvider(models.Model):
    _inherit = "llm.provider"

    def generate_transcription_schema(self, model_record):
        """Generate input/output schema for a transcription model."""
        return self._dispatch("generate_transcription_schema", model_record)

    def should_generate_transcription_schema(self, model_record):
        """Check whether a transcription model should get autogenerated schemas."""
        return self._dispatch("should_generate_transcription_schema", model_record)

    def translate_audio(
        self,
        data,
        filename,
        mimetype,
        source_language=None,
        target_language=None,
        **kwargs,
    ):
        """Speech translation. Providers opt in via <service>_translate_audio."""
        return self._dispatch(
            "translate_audio",
            data,
            filename,
            mimetype,
            source_language=source_language,
            target_language=target_language,
            **kwargs,
        )

    def supports_audio_translation(self):
        """Whether this provider can translate speech, not just transcribe it."""
        self.ensure_one()
        return bool(self.service) and hasattr(self, f"{self.service}_translate_audio")
