from odoo import models


class LLMProvider(models.Model):
    _inherit = "llm.provider"

    def generate_transcription_schema(self, model_record):
        """Generate input/output schema for a transcription model."""
        return self._dispatch("generate_transcription_schema", model_record)

    def should_generate_transcription_schema(self, model_record):
        """Check whether a transcription model should get autogenerated schemas."""
        return self._dispatch("should_generate_transcription_schema", model_record)
